/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package penjualan.view;
import java.sql.SQLException;
import penjualan.koneksi.koneksi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table. DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import penjualan.implement.transaksiimplement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class transaksiView extends javax.swing.JFrame {
    private DefaultTableModel model;
    /**
     * Creates new form transaksiView
     */
    public transaksiView() throws SQLException{
        initComponents();
        setLocationRelativeTo(null);
        model = new DefaultTableModel();
        tabelTransaksi.setModel(model);
        model.addColumn ("Kode Barang");
        model.addColumn ("Nama Barang");
        model.addColumn ("Harga");
        model.addColumn("Jumlah Beli");
        model.addColumn ("Subtotal");
        DateNow();
        genFak();
        setKodeBarang();
        setIdPelanggan();
        
    }
    
    private void setKodeBarang() throws SQLException {
        transaksiimplement getKdBrg = new transaksiimplement();
        ArrayList<String> urutanArr = getKdBrg.viewKdBrg(); 
        namaBarang.addItem("--Pilih--");
        for (String o: urutanArr) {
            namaBarang.addItem(o);
        }
    }

    private void setIdPelanggan() throws SQLException {
        transaksiimplement getIdPlg = new transaksiimplement(); 
        ArrayList<String> urutanArr = getIdPlg.viewIdPlg();
        nama.addItem("--Pilih--");
        for (String o: urutanArr) {
            nama.addItem(o);
        }
    }
    
    private void DateNow() {
        Date tglJual = new Date();
        SimpleDateFormat formatTgl = new SimpleDateFormat("yyyy-MM-dd");
        String dmy = formatTgl.format(tglJual);
        tgl_penjualan.setText(dmy);
    }
private int lastUrutan = 0;
    public void genFak() {
//        transaksiimplement getUrutan = new transaksiimplement();
//    int urutan = getUrutan.urutanDb();
//    Calendar now = Calendar.getInstance();
//    String kode_awal = "FJ";
//    int year = now.get(Calendar.YEAR) % 100; // Ambil 2 digit terakhir tahun
//    int month = now.get(Calendar.MONTH) + 1; // Ambil bulan, tambahkan 1 karena nilai bulan dimulai dari 0
//    int day = now.get(Calendar.DAY_OF_MONTH);
//    String urutanStr = String.format("%04d", urutan); // Format urutan menjadi 4 digit
//
//    // Buat nomor faktur
//    String result = String.format("%s-%02d%02d%02d-%s", kode_awal, year, month, day, urutanStr);
//
//    // Jika panjang result lebih dari panjang maksimum di kolom database, potong menjadi panjang maksimum
//    int maxNoFakturLength = 255; // Misalnya panjang maksimum di kolom database adalah 20
//    if (result.length() > maxNoFakturLength) {
//        result = result.substring(0, maxNoFakturLength);
//    }
//
//    no_faktur.setText(result);

// Mendapatkan urutan terakhir dari database
    transaksiimplement getUrutan = new transaksiimplement();
    lastUrutan = getUrutan.urutanDb();
    
    // Menambahkan 1 untuk nomor faktur berikutnya
    lastUrutan++;
    
    // Format nomor faktur sesuai dengan yang diinginkan, contoh: FJ-001, FJ-002, dst.
    String result = String.format("FJ-%03d", lastUrutan); // %03d berarti format 3 digit angka (001, 002, ...)
    
    // Setel nomor faktur di field no_faktur
    no_faktur.setText(result);
    }



    private void kosongkanDataPelanggan() {
        nama.setSelectedIndex(0);
        alamat.setText("");
        no_tlp.setText("");
    }
    
    private void kosongkanData() {
        jumlah.setText("");
        harga.setText("");
        namaBarang.setSelectedItem("--Pilih--");
        stok.setText("");
    }
    
    private void kosongkanDataTotalBayar() {
    totalBayar.setText("0");
}
    private void hitungTotalBayar () {
        int jmlRow = tabelTransaksi.getRowCount();
    double tot = 0;
    if (jmlRow == 0) {
        return;
    } else {
        for (int i = 0; i < jmlRow; i++) {
            double jmlTot = Double.valueOf(String.valueOf(model.getValueAt(i, 4)));
            tot += jmlTot;
        }
    }
    totalBayar.setText(String.valueOf(tot));
    }
    
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        no_tlp = new javax.swing.JTextField();
        nama = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        no_faktur = new javax.swing.JTextField();
        tgl_penjualan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        stok = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        namaBarang = new javax.swing.JComboBox<>();
        simpanKeranjang = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        totalBayar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        simpanTransaksi = new javax.swing.JButton();
        kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Data Pelanggan");

        jLabel2.setText("Nama Pelanggan");

        jLabel3.setText("Alamat");

        jLabel4.setText("No. Telp");

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });

        nama.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                namaItemStateChanged(evt);
            }
        });
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Data Barang");

        jLabel6.setText("No Faktur");

        jLabel7.setText("Tanggal Transaksi");

        jLabel8.setText("Nama Barang");

        jLabel9.setText("Stok Barang");

        jLabel10.setText("Harga");

        jLabel11.setText("Jumlah Pembelian");

        namaBarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                namaBarangItemStateChanged(evt);
            }
        });
        namaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaBarangActionPerformed(evt);
            }
        });

        simpanKeranjang.setText("Simpan ke Keranjang");
        simpanKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKeranjangActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga", "Jumlah Beli", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tabelTransaksi);

        jLabel12.setText("Total Pembayaran");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Transaksi Penjualan");

        simpanTransaksi.setText("Simpan Transaksi");
        simpanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanTransaksiActionPerformed(evt);
            }
        });

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1)
                        .addGap(279, 279, 279)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tgl_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(no_faktur, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(no_tlp, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel10)
                                                .addGap(69, 69, 69)
                                                .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(101, 101, 101)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jumlah))))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(33, 33, 33)
                                        .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(simpanKeranjang))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(hapus))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(353, 353, 353))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(kembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(simpanTransaksi)
                .addGap(304, 304, 304))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(no_faktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tgl_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(no_tlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(simpanKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(simpanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(kembali)
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void simpanKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanKeranjangActionPerformed
        // TODO add your handling code here:
        String kode = (String) namaBarang.getSelectedItem(); 
        String kodeFix = kode.substring(0, 4);
        String namaBrg = kode.substring(5, kode.length());
        double hrg = Double.parseDouble(harga.getText());
        int jml = Integer.parseInt(jumlah.getText());
        double subTot = hrg * jml;

        Object[] data = new Object[5];
        data[0] = kodeFix;
        data[1] = namaBrg;
        data[2] = String.valueOf(hrg);
        data[3] = String.valueOf(jml);
        data[4] = String.valueOf(subTot);

        model.addRow(data);
        this.hitungTotalBayar();
        this.kosongkanData();
    }//GEN-LAST:event_simpanKeranjangActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int delData = tabelTransaksi.getSelectedRow(); 
        if (delData == -1) {
            return;
        }else{
            model.removeRow(delData);
            this.hitungTotalBayar();
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void simpanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanTransaksiActionPerformed
        // TODO add your handling code here:
        String noFaktur = no_faktur.getText();
        String tanggal = tgl_penjualan.getText();
        String idPelanggan = (String) nama.getSelectedItem();
    
        try {
        // Simpan ke tabel Penjualan
            String queryPenjualan = "INSERT INTO penjualan (no_faktur, tgl_penjualan) VALUES ( ?, ?)";
            PreparedStatement psPenjualan = koneksi.getConnection().prepareStatement(queryPenjualan);
            psPenjualan.setString(1, noFaktur);
            psPenjualan.setString(2, tanggal);
            psPenjualan.executeUpdate();
        
            // Simpan ke tabel DetailJual untuk setiap item di tabel transaksi
            for (int i = 0; i < tabelTransaksi.getRowCount(); i++) {
            String kodeBarang = (String) tabelTransaksi.getValueAt(i, 0);
            int jumlahBeli = Integer.parseInt((String) tabelTransaksi.getValueAt(i, 3));
            
            String queryDetailJual = "INSERT INTO detailjual (no_faktur, kode_barang, jumlah) VALUES (?, ?, ?)";
            PreparedStatement psDetailJual = koneksi.getConnection().prepareStatement(queryDetailJual);
            psDetailJual.setString(1, noFaktur);
            psDetailJual.setString(2, kodeBarang);
            psDetailJual.setInt(3, jumlahBeli);
            psDetailJual.executeUpdate();
            
            // Kurangi stok barang di tabel barang
            String queryUpdateStok = "UPDATE barang SET stok_barang = stok_barang - ? WHERE kode_barang = ?";
            PreparedStatement psUpdateStok = koneksi.getConnection().prepareStatement(queryUpdateStok);
            psUpdateStok.setInt(1, jumlahBeli);
            psUpdateStok.setString(2, kodeBarang);
            psUpdateStok.executeUpdate();
        
        }
        
            JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan!");
        
            // Setelah menyimpan, kosongkan tabel transaksi dan form
            model.setRowCount(0);
            kosongkanDataPelanggan();
            kosongkanData();
            kosongkanDataTotalBayar();
            genFak();
        
        } catch (SQLException ex) {
        Logger.getLogger(transaksiView.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Transaksi gagal disimpan!");
    }
    }//GEN-LAST:event_simpanTransaksiActionPerformed

    private void namaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaBarangActionPerformed

    private void namaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_namaItemStateChanged
        // TODO add your handling code here:
        String kode = (String) nama.getSelectedItem();
        String kodeFix = kode.substring(0,4);
        try{
            Statement ktB=koneksi.getConnection().createStatement();
            ResultSet rsKBr=ktB.executeQuery("SELECT alamat, notelp FROM pelanggan where id_pelanggan = '"+ kodeFix +"'");
            while (rsKBr.next()){
                alamat.setText(rsKBr.getString("alamat"));
                no_tlp.setText(rsKBr.getString("notelp"));
            }
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_namaItemStateChanged

    private void namaBarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_namaBarangItemStateChanged
        // TODO add your handling code here:
         String kodeBrg = (String) namaBarang.getSelectedItem();
        String kodeFixBrg = kodeBrg.substring(0,4);
        try{
            Statement ktBrg =koneksi.getConnection().createStatement();
            ResultSet rsBrg=ktBrg.executeQuery("SELECT stok_barang, harga_barang FROM barang where kode_barang = '"+ kodeFixBrg +"'");
            while (rsBrg.next()){
                stok.setText(rsBrg.getString("stok_barang"));
                harga.setText(rsBrg.getString("harga_barang"));
            }
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_namaBarangItemStateChanged

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        this.dispose(); 
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new ToolbarMenu().setVisible(true);
        }
        }); 
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    new transaksiView().setVisible(true);
                }catch(SQLException ex){
                    Logger.getLogger(transaksiView.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton kembali;
    private javax.swing.JComboBox<String> nama;
    private javax.swing.JComboBox<String> namaBarang;
    private javax.swing.JTextField no_faktur;
    private javax.swing.JTextField no_tlp;
    private javax.swing.JButton simpanKeranjang;
    private javax.swing.JButton simpanTransaksi;
    private javax.swing.JTextField stok;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTextField tgl_penjualan;
    private javax.swing.JTextField totalBayar;
    // End of variables declaration//GEN-END:variables
}
